<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(tModLoaderPath)\tMLMod.targets" />
  <PropertyGroup>
    <AssemblyName>BetterTerraAchievements</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ModSourcePath>$(MSBuildProjectDirectory)</ModSourcePath>
  </PropertyGroup>
</Project>
